version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=2148448 # change this to your ID
       - API_HASH=afac821ab072847489f45f464f4fc63d # change this to your HASH
       - BOT_TOKEN=1599099989:AAEcSvhimIeCdub5XPFS6hcZCEe03dFAoyk #TGFileDownloadBot
       - BIN_CHANNEL=-1001672758629 # paste channel ID
      ports:
       - 1010:10
      volumes:
       - $HOME/TG-FileStreamBot:/app/.env
